name: Fix Sonar Issues with Pixeebot
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  share:
    name: Upload Semgrep Results to Pixeebot
    runs-on: ubuntu-latest
    steps:
      - uses: pixee/upload-tool-results-action@v1
        with:
          tool: Semgrep
          Semgrep-token: ${{ secrets.SEMGREP_APP_TOKEN }}
